### ISSUE TITLE
How to use the pipeline and have non-merged bam files as output?

### ISSUE THREAD

**Issue by chahatupreti** [ArimaGenomics/mapping_pipeline#1]
Hi,

We are using the Arima Hic-kit in our lab, and I have the fastq files (R1,R2) now. I want to analyze them using Hic-Pro but to use the mapping algorthm of Hic-Pro, it needs the cutting motif and the LIGATION_SITE information, which the kit does not provide. So, I am using the mapping pipeline as you have mentioned here to generate bam files from the fastq files and then, use the bam files for further analysis in HicPro. 

The issue is that HicPro requires separate bam files (for R1 and R2), and this mapping pipeline finally gives us one bam file with the information of R1 and R2 merged. I wanted to know how can I modify this pipeline so that I have 2 final bam files for the R1 and R2, so that I can then use it for downstream analysis?

Thank you,
Chahat

**Comment by ViriatoII** [comment]
I would say you just have to edit this part:

>echo "### Step 3A: Pair reads & mapping quality filter"
perl $COMBINER $FILT_DIR/HiC_1.bam $FILT_DIR/HiC_2.bam $SAMTOOLS $MAPQ_FILTER | $SAMTOOLS view -bS -t $FAIDX - | $SAMTOOLS sort -o $TMP_DIR/HiC.bam -

into:
>echo "### Step 3A: Not pairing reads & and not filtering based on map quality "
$SAMTOOLS view $FILT_DIR/HiC_1.bam -bS -t $FAIDX - | $SAMTOOLS sort -o $TMP_DIR/HiC_1.bam -
$SAMTOOLS view $FILT_DIR/HiC_2.bam -bS -t $FAIDX - | $SAMTOOLS sort -o $TMP_DIR/HiC_2.bam -

You would also need to edit the following commands to deal with HiC_1.bam and repeat for HiC_2.bam.
 The only problem I see here is that you don't do the mapping quality filter anymore.
