### ISSUE TITLE
issue at step 1.A FASTQ to BAM conversion

### ISSUE THREAD

**Issue by Samyuktha9624** [ArimaGenomics/mapping_pipeline#20]
Hello,

   I am using the Arima mapping pipeline bash script. I see the mapping worked at the first step of fastq to BAM conversion but always returns an empty .bam file, hindering the sequential steps. I have a doubt about this command,

echo "### Step 1.A: FASTQ to BAM (1st)"
$BWA mem -t $CPU $REF $IN_DIR/${SRA}_1.fastq.gz | $SAMTOOLS view -@ $CPU -Sb - > $RAW_DIR/${SRA}_1.bam

Why is the samtools view flag -Sb? Should it not be -bS for .sam to .bam conversion? What am I missing?

**Comment by xz-000** [comment]
"-Sb" and "-bS" should be equivalent for Samtools and won't affect your analysis. Maybe there were some other issues causing the error, such as memory or file issues.

**Comment by Samyuktha9624** [comment]
Thanks a lot for your reply, there was an issue with the files. I fixed it :)
