### ISSUE TITLE
Hardcoded path to samtools in get_stats.pl

### ISSUE THREAD

**Issue by olekto** [ArimaGenomics/mapping_pipeline#3]
Basically what the header says.  It is line 5, which contains:
open (FILE,"/projects/arima/Projects/RefFiles/software/samtools-0.1.18/samtools view $ARGV[0] |");

This will not work on machines where this path does not exist.

**Comment by xz-000** [comment]
Hi Tierhon,

That is a good catch! I have modified the code to remove the hard-coded path in the script.
One thing to note is that the users need to have "samtools" in their environment path to be able to run the script.

Thanks for your input!

--Arima Support Team
