### ISSUE TITLE
error in running two_read_bam_combiner.pl

### ISSUE THREAD

**Issue by christinawu2008** [ArimaGenomics/mapping_pipeline#5]
Hi,

I'm trying to run the perl script to combining read pairs, but got this error:
>Unrecognized character \x1F; marked by <-- HERE after <-- HERE near column 1 at R1_filtered.bam line 1.

Do you know what's going on with the filtered file?

Thanks
Chen

**Comment by xz-000** [comment]
Could you check the name of your raw reads to make sure that no special characters are there?
Check this post: https://stackoverflow.com/questions/30679352/using-control-character-x1f-with-string-and-or-stringbuilder

**Comment by christinawu2008** [comment]
This is the first line of my bam:

>D00626:344:CCA1FANXX:3:2308:1192:1930	16	tig00001764	394440	15	125M	*	0	0	GAACAGTTAACCCAGACAGGGCCTACTCAGATTCCTTCAAGCTCACAAGGAGAAGGCCAAATAAGCTCTCCAGTGGCTTCACACCATTCAGAAACCAGCACATCAGTGGCCAAGAGTCACCATTN	F@8D@GF090@0GGF>F=/:>=0;::0DCFDEB@>01>F>GFD?11D1>F>GGF@F=1B>GGGFGGEF<D>EGG@GFE1CDF1GF@GGGGGGCEGFCGGF1C>GGGGGFGFGGGCGGGGD=@<=#	NM:i:2	MD:Z:22A101C0	AS:i:115	XS:i:106	XA:Z:tig00005871,+28461,125M,3;tig00003520,-94920,125M,3;tig00007934,-301586,125M,4;tig00003588,-156867,125M,4;tig00020584,-121132,125M,4;

Which special characters do you recommend causing this problem?

Thank you!

**Comment by xz-000** [comment]
Since this error occurs at the 1st line of the bam file, could you please send us the first 1000 reads of your fastq files (not the final bam file) and detailed commands you used to: techsupport@arimagenomics.com
We can try to reproduce the error and take a close look. Thanks!
