### ISSUE TITLE
Reg: Post-Processing BAMs as per SALSA's recommendations

### ISSUE THREAD

**Issue by harish0201** [ArimaGenomics/mapping_pipeline#6]
Hi!

I did go through the mapping script that you have provided, but I do have a question, as I'll be using SALSA subsequent to this. I have the aligned BAMs sorted by co-ordinates as needed by SALSA. However they also recommend to use the filtering on this repo to minimize the artifacts.

Should I be pulling down the mapped reads (only mapped irrespective of SAM flags) from the aligned bams into R1 and R2 separately in a bam, then use the filter_five_end.pl script individually and recombine the bams?

Or shall I remap them in a single ended manner, and then combine them?

**Comment by xz-000** [comment]
Hi,

Thanks for your question! Yes, we recommend remapping them in a single ended manner and then filter and combine them using the filtering and the combining scripts.

Please let us know if you have further questions, thanks!

Best,
--Arima Customer Support Team

**Comment by harish0201** [comment]
Sure, I will do that, however, shouldn't extracting them from the paired bam using sam flags be the same?

Did you guys observe any difference between the two methods?

**Comment by xz-000** [comment]
It depends on how you align your raw reads, in a single-end mode or paired-end mode. And our combiner script also modifies the SAM flags. So it is not as the same as just extracting the reads using SAM flags. Hope it helps.

Best,
Arima Customer Support Team
